const cartActionTypes = {
  TOGGLE_DISPLAY_CART_DROPDOWN: 'TOGGLE_DISPLAY_CART_DROPDOWN',
  ADD_CART_ITEM: 'ADD_CART_ITEM',
  DELETE_CART_ITEM_BY_ID: 'DELETE_CART_ITEM_BY_ID',
  DECREMENT_CART_ITEM_QUANTITY: 'DECREMENT_CART_ITEM_QUANTITY',
  EMPTY_CART: 'EMPTY_CART'
};

export default cartActionTypes;
